config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :users do
    resources :cards
    resources :goals
  end

  resources :relationships

end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :emotions, presence: true
  validates :thoughts, presence: true
  validates :reflection, presence: true
  validates :intensity, presence: true

  belongs_to :user
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :card_count, presence: :true
  validates :start_date, presence: :true
  validates :end_date, presence: :true

  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :followed_through, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :follower_through, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followeds, through: :follower_through, source: :followed
  has_many :followers, through: :followed_through, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :cards
  has_one :goal

  enum access: [:user, :provider]

  def self.client_feed provider
    feed = []
    provider.followeds.each do |client|
      feed << { client_id: client.id, name: client.full_name, cards: client.cards.where("created_at > ?", provider.last_sign_in_at) }
    end
    feed
  end

  def goal_count
    ((cards.where(created_at: (goal.start_date)..(goal.end_date)).count.to_f / goal.card_count.to_f) * 100).round
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.search(query)
    where("email like ?", "#{query}%")
  end

  def followed user
    followeds.include? user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :city) } 
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def create
    @card = Card.new(card_params)
    @card.save
    if @card.save
      redirect_to(:back)
    else
      redirect_to(:back)
    end
  end

  private

  def card_params
    params.require(:card).permit(:emotions, :intensity, :thoughts, :reflection, :user_id)
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to (:back)
    else
      redirect_to (:back)
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      redirect_to (:back)
    else
      redirect_to (:back)
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:id, :user_id, :card_count, :start_date, :end_date)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    Relationship.create(relationship_params)
    redirect_to :back
  end

  def destroy
    target = Relationship.find_by(relationship_params)
    if target
      target.destroy
      redirect_to :back
    else
      flash[:error] = "Relationship does not exist"
      redirect_to :back
    end
  end

  private

  def relationship_params
    params.require(:relationship).permit(:followed_id, :follower_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
    @cards = @user.cards.sort_by(&:created_at).reverse
    @goal = @user.goal
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :city, :password, :current_password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include WelcomeHelper
  def index
    if current_user
      @cards = current_user.cards.sort_by(&:created_at).reverse
      @status_feed = current_user.followeds
      @clients = User.client_feed current_user
      @client_search = User.search(params[:query])
      @results = User.where(access: 0) || @client_search
      render 'dashboard'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_or_unfollow user
    if current_user.followed user
      render partial: 'unfollow', locals: {user: user}
    else
      render partial: 'follow', locals: {user: user}
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CbtCards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<!-- <p class="notice"><%= notice %></p> -->
<!-- <p class="alert"><%= alert %></p> -->
<%= render "welcome/sign_in_modal" %>
<%= render "welcome/sign_up_modal" %>
<% if current_user && current_user.provider? && @user %>
<%= render "users/new_goal" %>
<%= render "users/edit_goal" %>
<% elsif current_user %>
  <%= render "shared/new_card" %>
<% end %>
</body>
</html>

app/views/shared/_nav_btn.html.erb
<!-- Single button -->
<div class="button-container navbar-right">
  <div class="btn-group">
    <button type="button" id="menu" class="btn btn-info btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#">Account</a></li>
      <li><a href="#">Settings</a></li>
      <li><a href="#">Help</a></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
    </ul>
  </div>
</div>

app/views/shared/_new_card.html.erb
<div class="modal fade" id="new_card" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Card</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:card, :url => user_cards_path(current_user.id)) do |f| %>

        <input type="hidden" value="<%= current_user.id %>" name="card[user_id]">

        <div class="emotions-field">
          <%= f.label :emotions %><br>
          <%= f.text_field :emotions %>
        </div>

        <div class="intensity-field">
          <% intensity_arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>
          <%= f.label :intensity %><br />
          <%= f.select(:intensity, options_for_select(intensity_arr))%>
        </div>

        <div class="card-field">
          <%= f.label :thoughts %><br>
          <%= f.text_area :thoughts, { class: "form-control" } %>
        </div>

        <div class="card-field">
          <%= f.label :reflection %><br>
          <%= f.text_area :reflection, { class: "form-control"} %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit 'Add Card', { class: "btn btn-success"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_edit_goal.html.erb
<div class="modal fade" id="edit_goal" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Goal</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@goal, :url => user_goal_path(@goal.id, @user.id)) do |f| %>

        <input type="hidden" value="<%= @user.id %>" name="goal[user_id]">
        <input type="hidden" value="<%= Time.now %>" name="goal[start_date]">
        <input type="hidden" value="<%= Time.now + 7.days %>" name="goal[end_date]">

        <div class="intensity-field">
          <% goal_arr = [3, 5, 10] %>
          <%= f.label :count %><br />
          <%= f.select(:card_count, options_for_select(goal_arr))%>
        </div>

      </div>
      <div class="modal-footer">
        <%= f.submit 'Edit Goal', { class: "btn btn-success"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for Relationship.new do |f| %>
  <input type="hidden" value="<%= current_user.id %>" name="relationship[follower_id]">
  <input type="hidden" value="<%= user.id %>" name="relationship[followed_id]">
  <%= f.submit "Follow", :class => 'btn btn-success' %>
<% end %>

app/views/users/_new_card.html.erb
<div class="modal fade" id="new_card" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Card</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:card, :url => user_cards_path(current_user.id)) do |f| %>
        
        <input type="hidden" value="<%= current_user.id %>" name="card[user_id]">

        <div class="emotions-field">
          <%= f.label :emotions %><br>
          <%= f.text_field :emotions %>
        </div>

        <div class="intensity-field">
          <% intensity_arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>
          <%= f.label :intensity %><br />
          <%= f.select(:intensity, options_for_select(intensity_arr))%>
        </div>

        <div class="card-field">
          <%= f.label :thoughts %><br>
          <%= f.text_area :thoughts %>
        </div>

        <div class="card-field">
          <%= f.label :reflection %><br>
          <%= f.text_area :reflection %>
        </div>

      </div>
      <div class="modal-footer">
        <%= f.submit 'Add Card', { class: "btn btn-success"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_new_goal.html.erb
<div class="modal fade" id="new_goal" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Goal</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:goal, :url => user_goals_path(@user.id)) do |f| %>

        <input type="hidden" value="<%= @user.id %>" name="goal[user_id]">
        <input type="hidden" value="<%= Time.now %>" name="goal[start_date]">
        <input type="hidden" value="<%= Time.now + 7.days %>" name="goal[end_date]">

        <div class="intensity-field">
          <% goal_arr = [3, 5, 10] %>
          <%= f.label :count %><br />
          <%= f.select(:card_count, options_for_select(goal_arr))%>
        </div>

      </div>
      <div class="modal-footer">
        <%= f.submit 'Add Goal', { class: "btn btn-success"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_tag relationship_path(current_user, user), method: "delete" do |f| %>
    <input type="hidden" value="<%= current_user.id %>" name="relationship[follower_id]">
    <input type="hidden" value="<%= user.id %>" name="relationship[followed_id]">
  <%= submit_tag "Unfollow", :class => 'btn btn-success' %>
<% end %>

app/views/users/show.html.erb
<div class="content">
  <%= render "shared/nav_btn" %>
  <% if current_user.provider? %>
    <a class="navbar-brand" id="logo" href="/"><strong>CBT</strong>-Cards</brand><small> Provider</small></a>
    <div class="container" id="user-dash">
      <ul class="nav nav-pills" role="pilllist">
        <li class="u-dash active" role="presentation" class="active"><a href="#client-cards" aria-controls="client-cards" role="pill" data-toggle="pill"><%= @user.first_name + ' ' + @user.last_name  %>'s Cards</a></li>
        <li class="u-dash" role="presentation"><a href="#weekly-goal" aria-controls="client-goal" role="pill" data-toggle="pill">Weekly Goal</a</li>
        <li class="u-dash" role="presentation"><a href="#client-stats" aria-controls="client-stats" role="pill" data-toggle="pill"><%= @user.first_name + ' ' + @user.last_name  %>'s Stats</a></li>
      </ul><br>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="client-cards"><div class="col-md-6 col-md-offset-3">
          <% @cards.each do |card| %>
          <div class="list-group">
            <a href="/cards/<%= card.id %>" class="list-group-item">
              <p class="list-group-item-emotion"><strong>Emotions: </strong>
                <% @emotions = card.emotions.split(', ') %>
                <% @emotions.each do |emotion| %>
                <span class="label label-primary"><%= emotion %></span>
                <% end %>
              </p>
              <p class="list-group-item-intensity"><strong>Intensity: </strong><br><%= card.intensity %></p>
              <p class="list-group-item-thoughts"><strong>Thoughts: </strong><br><%= card.thoughts %></p>
              <p class="list-group-item-reflection"><strong>Reflection: </strong><br><%= card.reflection %></p>
            </a>
            <div class="edit">
              <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#annotate_card">Annotate</button>
            </div>
          </div>
          <% end %>
        </div></div>
        <div role="tabpanel" class="tab-pane" id="weekly-goal"><div class="col-md-6 col-md-offset-3">
          <div class="panel">
            <div class="stats">
              <br>
              <h2><%= @user.full_name %>'s Goal Settings</h2><br>
              <% if @user.goal %>
                <p><strong>Weekly Goal:</strong> <%= pluralize(@user.goal.card_count, 'Card') %></p>
                <p>
                  <%= "#{@user.goal.start_date.to_date.to_formatted_s(:long)} - #{@user.goal.end_date.to_date.to_formatted_s(:long)}"  %>
                  <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @user.goal_count %>" aria-valuemin="0" aria-valuemax="100" style="width:<%= @user.goal_count %>%">
                      <%= @user.goal_count %>%
                    </div>
                  </div>
                </p><br>
                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#edit_goal">Edit Goal</button>
              <% else %>
                <p><em>No weekly goal set.</em></p>
                <br><br>
              <% end %>
              <% unless @user.goal %>
                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new_goal">New Goal</button>
              <% end %>
            </div>
          </div>
       </div></div>
        <div role="tabpanel" class="tab-pane" id="client-stats"><div class="col-md-8 col-md-offset-2">
          <div class="panel">
            <br>
            <h2 class="user-heading"><%= @user.full_name %>'s Profile</h2><br>
            <ul class="profile">
              <li><strong>First Name: </strong><%= @user.first_name %></li>
              <li><strong>Last Name: </strong><%= @user.last_name %></li>
              <li><strong>Email: </strong><%= @user.email %></li>
              <li><strong>Card Count: </strong><%= @user.cards.count %></li>
              <br>
              <%= follow_or_unfollow @user %><br>
            </div>
          </div></div>
    <% end %>
  </div>
</div>

app/views/welcome/_sign_in_modal.html.erb
<div class="modal fade" id="signin" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:user, :url => session_path(:user)) do |f| %>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.text_field :email %>
        </div>

        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password %>
        </div>

        <div class="field">
          <%= f.label :remember_me %>
          <%= f.check_box :remember_me %>
        </div>

        <div class="field">
          <%= link_to "Forgot your password?", new_password_path(:user) %>
        </div>

      </div>
      <div class="modal-footer">
        <%= f.submit 'Sign In', { class: "btn btn-primary"} %>
        <!-- <button type="button" class="btn btn-primary">Sign In</button> -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_sign_up_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">

      <%= form_for(:user, :url => registration_path(:user)) do |f| %>
        <%= devise_error_messages! %>

      <div class="field">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name %>
      </div>

      <div class="field">
        <%= f.label :city %><br />
        <%= f.text_field :city, :value => "eg. Austin, TX" %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      </div>
      <div class="modal-footer">
        <%= f.submit 'Sign In', { class: "btn btn-primary"} %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/_signin_modal.html.erb
<div class="modal fade" id="signin" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:user, :url => session_path(:user)) do |f| %>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.text_field :email %>
        </div>

        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password %>
        </div>

        <div class="field">
          <%= f.label :remember_me %>
          <%= f.check_box :remember_me %>
        </div>

        <div class="field">
          <%= link_to "Forgot your password?", new_password_path(:user) %>
        </div>

      </div>
      <div class="modal-footer">
        <%= f.submit 'Sign In', { class: "btn btn-primary"} %>
        <!-- <button type="button" class="btn btn-primary">Sign In</button> -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_signup_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog" arial-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" arial-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">

      </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-primary">Sign Up</button>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="welcome_header">
    <h1><strong>CBT</strong>-Cards</h1>
    <p><strong>C</strong>ognitive <strong>B</strong>ehavior <strong>T</strong>herapy Cards</p>
    <h4>Track troublesome thoughts.</h4>
    <h4>Understand your cognitive distortion patterns.</h4>
    <h4>Get in control.</h4>
  </div>
</div>

<div class="start">
  <button type="button" class="btn btn-info btn-lg raised" data-toggle="modal" data-target="#signup">Start</button>
  <br><br>
  <p>or</p>
  <%= link_to "Sign-in", "#", data: { toggle: "modal", target: "#signin" } %>
</div>